# Generated by Django 3.2.4 on 2022-05-27 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='nombre',
            new_name='name',
        ),
    ]
